services:
  db:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppassword
      POSTGRES_DB: shopdb
    ports:
      - "5433:5432"
    volumes:
      - shop-data-volume:/var/lib/postgresql
volumes:
  shop-data-volume: